services:
  patient-service-db:
    image: postgres:15
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - patient-service-db-data:/var/lib/postgresql/data
      # This is the crucial part: it runs our script on startup
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - internal-patient-service-network
    healthcheck:
      # This simpler healthcheck just confirms the server is running
      test: ["CMD-SHELL", "pg_isready -U admin_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  patient-service:
    build:
      context: .
      args:
        SERVICE_JAR_PATH: /app/patient-service/target/patient-service-0.0.1-SNAPSHOT.jar
    container_name: patient-service-app
    ports:
      - "8888:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db?sslmode=disable
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9090
    depends_on:
      patient-service-db:
        condition: service_healthy
    networks:
      - internal-patient-service-network

  billing-service:
    build:
      context: .
      args:
        SERVICE_JAR_PATH: /app/billing-service/target/billing-service-0.0.1-SNAPSHOT.jar
    container_name: billing-service-app
    ports:
      - "4001:8081"
      - "9091:9090"
    environment:
      SERVER_PORT: 8081
      GRPC_SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/billing_db?sslmode=disable
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      patient-service-db:
        condition: service_healthy
    networks:
      - internal-patient-service-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,EXTERNAL://0.0.0.0:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "DPpBDo-lQ_u-gN_-bZg0eg"
    networks:
      - internal-patient-service-network

volumes:
  patient-service-db-data:

networks:
  internal-patient-service-network:
    driver: bridge
