spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # --- Auth Service Route ---
            - id: auth-service-route
              # Forwards to your local machine on port 8083
              uri: http://localhost:8083
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            # --- Patient Service Route ---
            - id: patient-service-api-route
              # Forwards to your local machine on port 8080
              uri: http://localhost:8080
              predicates:
                - Path=/patients/**

            # --- Add other services here as you build them ---
